#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

networks:

    my-net:
        name: immich-net

services:

    immich-server:
        container_name: immich-server
        hostname: immich-server
        restart: unless-stopped
        image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
        command: ['start.sh', 'immich']
        environment:
            REDIS_HOSTNAME: immich-redis
            DB_DATABASE_NAME: ${IMMICH_DB_NAME}
            DB_PASSWORD: ${IMMICH_DB_PWD}
            DB_USERNAME: ${IMMICH_DB_USER}
            DB_HOSTNAME: immich-db
        volumes:
            - uploads:/usr/src/app/upload
        ports:
            - $IMMICH_PORT:3001
        depends_on:
            - redis
            - database
        networks:
            - my-net

    immich-microservices:
        container_name: immich-microservices
        hostname: immich-microservices
        restart: unless-stopped
        image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
        #   file: hwaccel.transcoding.yml
        #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
        command: ['start.sh', 'microservices']
        environment:
            REDIS_HOSTNAME: immich-redis
            DB_DATABASE_NAME: ${IMMICH_DB_NAME}
            DB_PASSWORD: ${IMMICH_DB_PWD}
            DB_USERNAME: ${IMMICH_DB_USER}
            DB_HOSTNAME: immich-db
        volumes:
            - uploads:/usr/src/app/upload
        depends_on:
            - redis
            - database
        networks:
            - my-net

    immich-machine-learning:
        container_name: immich-machine-learning
        hostname: immich-machine-learning
        restart: unless-stopped
        # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
        # Example tag: ${IMMICH_VERSION:-release}-cuda
        image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        #   file: hwaccel.ml.yml
        #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable    
        volumes:
            - machine-learning:/cache
        networks:
            - my-net

    redis:
        container_name: immich-redis
        hostname: immich-redis
        restart: unless-stopped
        image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
        networks:
            - my-net

    database:
        container_name: immich-db
        hostname: immich-db
        restart: unless-stopped
        image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
        environment:
            POSTGRES_PASSWORD: ${IMMICH_DB_PWD}
            POSTGRES_USER: ${IMMICH_DB_USER}
            POSTGRES_DB: ${IMMICH_DB_NAME}
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - my-net

volumes:

    uploads:
    machine-learning:
    db: